version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine@sha256:0985e772fb9f729e6fa0980da05fca5d9c468e870eed43071545afa9d2e27d94
    ports:
      - '7070:7070'
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      grafana:
        condition: service_healthy
    restart: always

  grafana:
    image: grafana/otel-lgtm@sha256:d6c52678ab5b7144f27ae569fd778608121c0f4a10eb411983750a0d67c1fbe3
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'
    networks:
      - backend

networks:
  backend:
    driver: bridge
