version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine@sha256:67cbbcc757a6ce913b33e515b020cfd3923897ad883c452903b1e3487a95a570
    ports:
      - '7070:7070'
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      grafana:
        condition: service_healthy
    restart: always

  grafana:
    image: grafana/otel-lgtm@sha256:3006944a3b1f37d36be5a982eb8c8b3b1448a9c82699226532b6630f21fa637c
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'
    networks:
      - backend

networks:
  backend:
    driver: bridge
