// Generated by weaver from the embrace-semconv registry. Do not edit: run `make generate` in
// packages/web-sdk/semconv/ instead.

/**
 * UUID identifying the session part that the telemetry was recorded in. A user session is composed of one or more consecutive session parts.
 */
export const KEY_EMB_SESSION_PART_ID = 'emb.session_part_id';

/**
 * UUID identifying the user session that the telemetry was recorded in.
 */
export const KEY_EMB_USER_SESSION_ID = 'emb.user_session_id';
