// Generated by weaver from the embrace-semconv registry. Do not edit: run `make generate` in
// packages/web-sdk/semconv/ instead.
export {
  KEY_EMB_SESSION_PART_ID,
  KEY_EMB_USER_SESSION_ID,
} from './attributes.ts';
