version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/cli'
      - '/demo/frontend'
      - '/demo/frontend-cdn'
      - '/demo/webpack-example'
      - '/tests/performance'
      - '/tests/integration'

    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 50
    groups:
      eslint:
        patterns:
          - '*eslint*'
      # All these packages are marked as experimental, so only apply patch updates
      opentelemetry-experimental:
        patterns:
          - '@opentelemetry/api-logs'
          - '@opentelemetry/instrumentation*'
          - '@opentelemetry/opentelemetry-browser-detector'
          - '@opentelemetry/otlp-*'
          - '@opentelemetry/sdk-logs'
          - '@opentelemetry/web-common'
        update-types:
          - patch
      opentelemetry:
        patterns:
          - '@opentelemetry/*'
        update-types:
          - minor
      react:
        patterns:
          - 'react*'
