version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/cli'
      - '/demo/frontend'
      - '/demo/frontend-cdn'
      - '/demo/webpack-example'
      - '/tests/performance'
      - '/tests/integration'

    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 50
    ignore:
      - dependency-name: 'webpack'
        versions: ['>=5.0.0']
        directories: ['/tests/integration/platforms/webpack-4']
      - dependency-name: 'webpack-cli'
        versions: ['>=5.0.0']
        directories: ['/tests/integration/platforms/webpack-4']
      - dependency-name: 'webpack-dev-server'
        versions: ['>=5.0.0']
        directories: ['/tests/integration/platforms/webpack-4']
      - dependency-name: 'html-webpack-plugin'
        versions: ['>=5.0.0']
        directories: ['/tests/integration/platforms/webpack-4']
    groups:
      vite:
        patterns:
          - '*vite*'
      otel:
        patterns:
          - '@opentelemetry*'
      eslint:
        patterns:
          - '*eslint*'
      react:
        patterns:
          - 'react*'
          - '*/react*'
      playwright:
        patterns:
          - '*playwright*'
