version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/cli'
      - '/demo/frontend'
      - '/demo/frontend-cdn'
      - '/demo/frontend-sdk'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 50
    groups:
      vite:
        patterns:
          - '*vite*'
      opentelemetry:
        patterns:
          - '@opentelemetry*'
      eslint:
        patterns:
          - '*eslint*'
      react:
        patterns:
          - 'react*'
          - '*/react*'
      playwright:
        patterns:
          - '*playwright*'
          - '*chrome*'
