categories:
  - title: 'Changes'
  - title: 'Dependencies'
    collapse-after: 5
    labels:
      - 'dependencies'

version-template: $MAJOR.$MINOR

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
