export {
  MAIN_THREAD_TIME_THRESHOLD_IN_MS,
  SCRIPT_EVAL_THRESHOLD_IN_MS,
  TOTAL_BLOCKING_TIME_THRESHOLD_IN_MS,
  TOTAL_HEAP_SIZE_THRESHOLD_IN_MB,
  TOTAL_SCRIPT_DURATION_THRESHOLD_IN_MS,
  TOTAL_SIZE_OF_REQUESTS_THRESHOLD_IN_KB,
  TOTAL_TASK_DURATION_THRESHOLD_IN_MS,
} from './thresholds.js';
