const getFromEnv = (key: string, defaultValue: number): number => {
  const value = process.env[key];

  return value ? parseInt(value, 10) : defaultValue;
};

const TOTAL_SIZE_OF_REQUESTS_THRESHOLD_IN_KB = getFromEnv(
  'TOTAL_SIZE_OF_REQUESTS_THRESHOLD_IN_KB',
  50,
);
const TOTAL_SCRIPT_DURATION_THRESHOLD_IN_MS = getFromEnv(
  'TOTAL_SCRIPT_DURATION_THRESHOLD_IN_MS',
  150,
);
const TOTAL_TASK_DURATION_THRESHOLD_IN_MS = getFromEnv(
  'TOTAL_TASK_DURATION_THRESHOLD_IN_MS',
  1000,
);
const TOTAL_HEAP_SIZE_THRESHOLD_IN_MB = getFromEnv(
  'TOTAL_HEAP_SIZE_THRESHOLD_IN_MB',
  16,
);
const TOTAL_BLOCKING_TIME_THRESHOLD_IN_MS = getFromEnv(
  'TOTAL_BLOCKING_TIME_THRESHOLD_IN_MS',
  100,
);
const MAIN_THREAD_TIME_THRESHOLD_IN_MS = getFromEnv(
  'MAIN_THREAD_TIME_THRESHOLD_IN_MS',
  150,
);
const SCRIPT_EVAL_THRESHOLD_IN_MS = getFromEnv('SCRIPT_EVAL_THRESHOLD', 150);

export {
  MAIN_THREAD_TIME_THRESHOLD_IN_MS,
  SCRIPT_EVAL_THRESHOLD_IN_MS,
  TOTAL_BLOCKING_TIME_THRESHOLD_IN_MS,
  TOTAL_HEAP_SIZE_THRESHOLD_IN_MB,
  TOTAL_SCRIPT_DURATION_THRESHOLD_IN_MS,
  TOTAL_SIZE_OF_REQUESTS_THRESHOLD_IN_KB,
  TOTAL_TASK_DURATION_THRESHOLD_IN_MS,
};
