// Generated by weaver from the embrace-semconv registry. Do not edit: run `make generate` in
// packages/web-sdk/semconv/ instead.

/**
 * A fixture attribute with a long key, so templates that wrap long lines are exercised.
 */
export const KEY_FIXTURE_A_LONG_ATTRIBUTE_KEY_THAT_MAKES_GENERATED_LINES_WRAP_IN_MOST_FORMATTERS =
  'fixture.a_long_attribute_key_that_makes_generated_lines_wrap_in_most_formatters';

/**
 * A fixture enum attribute.
 */
export const KEY_FIXTURE_ENUM = 'fixture.enum';

/**
 * A deprecated fixture attribute, so templates that mark deprecation are exercised.
 * @deprecated Replaced by `fixture.str`.
 */
export const KEY_FIXTURE_OLD_STR = 'fixture.old_str';

/**
 * A fixture string attribute.
 */
export const KEY_FIXTURE_STR = 'fixture.str';
