// Generated by weaver from the embrace-semconv registry. Do not edit: run `make generate` in
// packages/web-sdk/semconv/ instead.
export {
  KEY_FIXTURE_A_LONG_ATTRIBUTE_KEY_THAT_MAKES_GENERATED_LINES_WRAP_IN_MOST_FORMATTERS,
  KEY_FIXTURE_ENUM,
  KEY_FIXTURE_OLD_STR,
  KEY_FIXTURE_STR,
} from './attributes.ts';
