name: Autolabel PR
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write

jobs:
  autolabeler:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: release-drafter/release-drafter/autolabeler@v7
