name: Draft Release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  next-release:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: release-drafter/release-drafter@139054aeaa9adc52ab36ddf67437541f039b88e2 # v7.1.1
        with:
          # only create a release if the last commit merged starts with "release". Coming from .github/workflows/release.yaml
          disable-releaser: ${{ !startsWith(github.event.head_commit.message, 'release') }}
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
